Some extras used at Feeld
NorfairKing/haskell-dangerous-functions pull request #16
Opened 2021-10-19 09:26 UTC by TheOddler

2021-10-19 09:27 UTC, TheOddler commented on README.md
> +`O(n^2)`.
I wasn't sure if there is an alternative we can use here?

2021-10-19 09:29 UTC, NorfairKing commented on README.md
> +`O(n^2)`.
Not really; a better datastructure..

2021-10-19 09:38 UTC, NorfairKing commented on README.md
> +Using `const a` instead of `\_ -> a` is usually less clear instead of more clear.
I don't think we should put const on this list. It's not dangerous.

2021-10-19 09:53 UTC, NorfairKing commented on hlint.yaml
>    - {name: Prelude.error, within: []}
It's already here

2021-10-19 09:54 UTC, NorfairKing commented on hlint.yaml
> +- ignore: { name: "Use if" } # Sometimes using a case-match is fine.
We don't need to add these, they're not dangerous.

2021-10-19 09:54 UTC, NorfairKing commented on README.md
> +Althought not a function, this hint doesn't actually help, especially not in tests.
Same here, not dangerous.

2021-10-19 09:56 UTC, NorfairKing requested changes
I understand err-ing on the safe side, but some of these are not dangerous so let's not put them here.

2021-10-23 17:24 UTC, NorfairKing commented on README.md
> +`O(n^2)`.
Also it turns out this was wrong, see the concat benchmark in the repository.

2025-02-23 21:57 UTC, closed without merging